app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('peliculas/', views.peliculas, name='peliculas'),
    path('peliculas/<int:id>/', views.pelicula, name='pelicula'),
]

bluck/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'app/index.html')


lista = [
    {'id': 0, 'nombre': 'Pulp Fiction', 'year': 1998},
    {'id': 1, 'nombre': 'The Hateful Eight', 'year': 2015},
    {'id': 2, 'nombre': 'Django Unchained', 'year': 2010},
    {'id': 3, 'nombre': 'Kill Bill Vol. 1', 'year': 2004},
]

def peliculas(request):
    contexto = {
        'lista_peliculas': lista,
        'year': 2020,
        'tienda': 'Bluckbuster'
    }
    return render(request, 'app/peliculas.html',contexto)

def pelicula(request, id):
    contexto = {}
    if id < len(id):
        contexto['pelicula'] = lista[id]
    return render(request, 'app/pelicula.html', contexto)

app/templates/app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blockbuster</title>
    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
</head>
<body>
    <h1>BLOCKBUSTER</h1>
    <h3>BIENVENIDO A SU TIENDA DE CONFIANZA</h3>
    <a href="{% url 'app:peliculas' %}">Peliculas</a>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quas numquam porro nulla adipisci aperiam, ut labore cum in dolore soluta debitis fuga. Quidem quos est sed laboriosam esse deleniti eum!</p>
    <hr>
    <h3>Todos los derechos reservados</h3>
    <script src="{% static 'app/js/index.js' %}"></script>
</body>
</html>

app/templates/app/pelicula.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peliculas</title>
</head>
<body>
    {% if pelicula %}
    <h1>{{ pelicula.nombre }}</h1>
    <h3>{{ pelicula.year }}</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa maxime voluptatibus perspiciatis vitae consequuntur alias officiis non illum, nemo assumenda tempore, veniam doloribus, ducimus placeat voluptate sapiente fugiat quibusdam necessitatibus?</p>
    {% else %}
    <h1>La pelicula solicitada no existe</h1>
    {% endif %}
</body>
</html>

app/templates/app/peliculas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Peliculas</title>
</head>
<body>
    <h1>Bienvenido a peliculas</h1>
    <table border="1px" width=100%>
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Año</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for p in lista_peliculas %}
            <tr>
                <td>{{ p.nombre }}</td>
                <td>{{ p.year }}</td>
                <td><a href="{% url 'app:pelicula' p.id %}">Ver</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>